testname: >-
  Deep Neural Network based Music Source Separation -
  Multiple Stimuli with Hidden Reference and Anchor Test
testId: deep
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php

pages:
  - type: generic
    id: first_page
    name: webMUSHRA
    content: Deep Neural Network based Music Source Separation - Listening Test
  - type: consent
    id: consent_page
    name: Consent
    mustConsent: true
    content: |-
      <p>
        You are participating in a listening test.
      </p>
      <p>
        To complete this test, you will be asked to compare a selection of audio
        samples against a reference audio sample. The test should take between 5
        to 10 minutes in total.
      </p>
      <p>
        For research purposes we want to store the answers you give during the
        test.
      </p>
        All data will be stored anonymously behind a password. Any personal
        information will be destroyed after research has been been completed and
        will adhere to The Data Protection Act 2018 (GDPR).
      </p>
      <p>
        Do you give consent for this?
      </p>
  - type: mushra
    id: training
    name: webMUSHRA Training Page
    content: |-
      <p>
        This training page shows how to use our user interface. Please perform
        the instructions to proceed with the training session.
      </p>
      <p>
        In this test you are asked to rate the Basic Audio Quality (BAQ) of each
        condition.
      </p>
      <p>
        Basic Audio Quality is a single and global attribute that is used to
        judge any and all detected differences between the reference and the
        condition.
      </p>
      <p>
        When you press play, you will hear an audio sample of a sine wave.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and 0
        being completely different.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/stereo_mono_ref.flac
    stimuli:
      C1: configs/resources/audio/stereo_mono_c1.flac
      C2: configs/resources/audio/stereo_mono_c2.flac
      C3: configs/resources/audio/stereo_mono_c3.flac
  - type: mushra
    id: test_a
    name: Audio Stimuli Testing A
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/a1_folk_solo_ref_drum.flac
    stimuli:
      C1: configs/resources/audio/a2_folk_mix_drums_ripx.flac
      C2: configs/resources/audio/a2_folk_mix_drums_demucs4_ht_drums.flac
      C3: configs/resources/audio/a2_folk_mix_drums_rx.flac
      C4: configs/resources/audio/a2_folk_mix_drums_lalalai.flac
      C5: configs/resources/audio/a3_folk_solo_ref_drums_anchor_standard_low_3500hz.flac
  - type: mushra
    id: test_b
    name: Audio Stimuli Testing B
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/b1_folk_solo_ref_gtr.flac
    stimuli:
      C1: configs/resources/audio/b3_folk_solo_ref_gtr_anchor_standard_low_3500hz.flac
      C2: configs/resources/audio/b2_folk_mix_gtr_demucs4_ht_other.flac
      C3: configs/resources/audio/b2_folk_mix_gtr_ripx.flac
      C4: configs/resources/audio/b2_folk_mix_gtr_lalalai.flac
      C5: configs/resources/audio/b2_folk_mix_gtr_rx.flac
  - type: mushra
    id: test_c
    name: Audio Stimuli Testing C
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/c1_rock_solo_ref_drums.flac
    stimuli:
      C1: configs/resources/audio/c2_rock_mix_drums_rx.flac
      C2: configs/resources/audio/c3_rock_solo_ref_drums_anchor_standard_low_3500hz.flac
      C3: configs/resources/audio/c2_rock_mix_drums_ripx.flac
      C4: configs/resources/audio/c2_rock_mix_drums_lalalai.flac
      C5: configs/resources/audio/c2_rock_mix_drums_demucs4_ht_drums.flac
  - type: mushra
    id: test_d
    name: Audio Stimuli Testing D
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/d1_rock_solo_ref_gtr.flac
    stimuli:
      C1: configs/resources/audio/d2_rock_mix_gtr_demucs4_ht_other.flac
      C2: configs/resources/audio/d2_rock_mix_gtr_rx.flac
      C3: configs/resources/audio/d2_rock_mix_gtr_ripx.flac
      C4: configs/resources/audio/d2_rock_mix_gtr_lalalai.flac
      C5: configs/resources/audio/d3_rock_solo_ref_gtr_anchor_standard_low_3500hz.flac
  - type: mushra
    id: test_e
    name: Audio Stimuli Testing E
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/e1_silver_moon_vox_od_solo_ref.flac
    stimuli:
      C1: configs/resources/audio/e2_silver_moon_vox_live_rx.flac
      C2: configs/resources/audio/e3_silver_moon_vox_od_anchor_standard_low_3500hz.flac
      C3: configs/resources/audio/e2_silver_moon_vox_live_lalalai.flac
      C4: configs/resources/audio/e2_silver_moon_vox_live_demucs4_ht_other.flac
      C5: configs/resources/audio/e2_silver_moon_vox_live_ripx.flac
  - type: mushra
    id: test_f
    name: Audio Stimuli Testing F
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/f1_silver_moon_bass_od_solo_ref.flac
    stimuli:
      C1: configs/resources/audio/f2_silver_moon_bass_live_demucs4_ht_bass.flac
      C2: configs/resources/audio/f2_silver_moon_bass_live_rx.flac
      C3: configs/resources/audio/f3_silver_moon_bass_od_anchor_3500hz.flac
      C4: configs/resources/audio/f2_silver_moon_bass_live_lalalai.flac
      C5: configs/resources/audio/f2_silver_moon_bass_live_ripx.flac
  - type: mushra
    id: test_g
    name: Audio Stimuli Testing G
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/g1_silver_moon_gtr_od_solo_ref.flac
    stimuli:
      C1: configs/resources/audio/g2_silver_moon_gtrs_live_ripx.flac
      C2: configs/resources/audio/g3_silver_moon_gtr_od_anchor_standard_low_3500hz.flac
      C3: configs/resources/audio/g2_silver_moon_gtrs_live_lalalai.flac
      C4: configs/resources/audio/g2_silver_moon_gtrs_live_demucs4_ht_other.flac
      C5: configs/resources/audio/g2_silver_moon_gtrs_live_rx1.flac
  - type: mushra
    id: test_h
    name: Audio Stimuli Testing H
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/h1_folk1_mix_ref_isolated.flac
    stimuli:
      C1: configs/resources/audio/h2_folk1_mix_rx.flac
      C2: configs/resources/audio/h2_folk1_mix_raw.flac
      C3: configs/resources/audio/h2_folk1_mix_demucs4-ht.flac
      C4: configs/resources/audio/h3_folk1_mix_anchor_standard_low_3500hz.flac
      C5: configs/resources/audio/h2_folk1_mix_lalalai.flac
      C6: configs/resources/audio/h2_folk1_mix_ripx.flac
  - type: mushra
    id: test_i
    name: Audio Stimuli Testing I
    content: |-
      <p>
        Please listen and rate each piece of test audio (conditions) from 0 to
        100, with 100 being judged to be identical to the reference audio and
        0 being completely different.
      </p>
      <p>
        For best results, play the reference audio first and then each
        subsequent test audio sample.
      </p>
      <p>
        You can switch between each audio sample at any time.
      </p>
      <p>
        You can also use the sliders to adjust the start and end points of the
        audio sample loop to find identical looping sections.
      </p>
      <p>
        You are being asked to rate by audio quality not musical content.
      </p>
      <p>
        Click next once you have rated every audio sample.
      </p>
    showWaveform: true
    enableLooping: true
    reference: configs/resources/audio/i1_rock1_mix_ref_isolated.flac
    stimuli:
      C1: configs/resources/audio/i2_rock1_mix_lalalai.flac
      C2: configs/resources/audio/i2_rock1_mix_ripx.flac
      C3: configs/resources/audio/i2_rock1_mix_demucs4-ht.flac
      C4: configs/resources/audio/i3_rock1_mix_anchor_standard_low_3500hz.flac
      C5: configs/resources/audio/i2_rock1_mix_rx.flac
      C6: configs/resources/audio/i2_rock1_mix_raw.flac
  - type: finish
    name: Thank you
    content: Thank you for attending!
    showResults: true
    writeResults: true
    questionnaire:
      - type: number
        name: age
        label: Age
        min: 0
        max: 100
        default: 0
      - type: likert
        name: role
        label: Role
        response:
          - value: engineer
            label: Trained / Professional Audio Engineer
          - value: student
            label: Audio Engineering Student
          - value: nota
            label: None of the above
      - type: likert
        name: equipment
        label: What did you use during the test to listen?
        response:
          - value: studio speakers
            label: High quality studio speakers
          - value: hifi speakers
            label: Home hi-fi speakers (bookshelf or floorstanding)
          - value: bluetooth speakers
            label: Portable bluetooth speakers
          - value: over-ear headphones
            label: Over-ear Headphones
          - value: in-ear earphones
            label: In-ear earphones
          - value: nota
            label: None of the above (fill-in below)
      - type: text
        name: equipment_other
        label: Other equipment (if none of the above)
        optional: true
